export const IMAGES = {
    logo: '/Logo-compressor.png',
    cards: [
        '/cards/icon-visa-compressor.png',
        '/cards/icon-master-compressor.png',
        '/cards/icon-america-compressor.png',
        '/cards/icon-cover-compressor.png',
        '/cards/icon-discovery-compressor.png',
        '/cards/icon-paypal-compressor.png',
        '/cards/icon-masteri-compressor.png',
    ],
    mainSlide: ['/mainSlideImgs/Slide1.webp', '/mainSlideImgs/Slide2.webp', '/mainSlideImgs/Slide3.webp'],
    collections: [
        "/collectionImgs/image-collection-1.avif",
        "/collectionImgs/image-collection-2.avif",
        "/collectionImgs/image-collection-3.avif",
        "/collectionImgs/image-collection-4.avif",
        "/collectionImgs/image-collection-5.avif",
    ],
    watches: [
        "/watches/watch1.webp",
        "/watches/watch2.webp",
        "/watches/watch3.webp",
        "/watches/watch4.webp",
        "/watches/watch5.webp",
        "/watches/watch6.webp",
        "/watches/watch7.webp",
        "/watches/watch8.webp",
        "/watches/watch9.webp",
        "/watches/watch10.webp",
        "/watches/watch11.webp",
        "/watches/watch12.webp",
        "/watches/watch13.webp",
        "/watches/watch14.webp",
        "/watches/watch15.webp",
        "/watches/watch16.webp",
        "/watches/watch17.webp",
        "/watches/watch18.webp",
    ],
    instagram: [
        "/instagramImgs/image1.jpg",
        "/instagramImgs/image2.webp",
        "/instagramImgs/image3.jpg",
        "/instagramImgs/image4.jpg",
        "/instagramImgs/image5.webp",
        "/instagramImgs/image6.jpg",
        "/instagramImgs/image7.webp",
        "/instagramImgs/image8.jpg",
        "/instagramImgs/image9.webp",
        "/instagramImgs/image10.webp",
        "/instagramImgs/image11.jpg",
        "/instagramImgs/image12.jpg",
        "/instagramImgs/image13.webp",
        "/instagramImgs/image14.webp",
        "/instagramImgs/image15.jpg",
        "/instagramImgs/image16.webp",
    ],
    customBlock: ['/customBlock/custom-block-1.webp', '/customBlock/custom-block-2.webp', '/customBlock/custom-block-3.webp']
}