import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { seeders } from '@/seeders'

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '600', '700'] })
seeders()
export const metadata: Metadata = {
  title: 'watches-theme',

  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
